### ISSUE TITLE
Alternate name for UTC +5:30?

### ISSUE THREAD

**Issue by anirvan** [andytlr/homeslice#13]
UTC +5:30 is the time zone for India and Sri Lanka. Right now, the city name for the time zone is Colombo, but it might be easier for end users if you used a better-known city like Mumbai (the most populous city in the time zone) or New Delhi (possibly the best-known city in the time zone). Thanks.

**Comment by andytlr** [comment]
I wanted to use Mumbai, however I'm using [Moment Timezone](http://momentjs.com/timezone/) which doesn't seem to include it. That link contains a map with all the available cities.

I was originally just using GMT offsets, which meant I could define any city as long as I knew the offset. But that didn't account for daylight savings. It seemed much more robust to use a library to handle this.

What I can do is use the timezone from another city, e.g. using Colombo's:

``` Javascript
"colombo": ["Colombo", "Asia/Colombo"]
```

But using Mumbai's details:

``` Javascript
"mumbai": ["Mumbai", "Asia/Colombo"]
```

But I didn't want to do this unless I was 100% sure these cities would always have the same time. Do you know if this is the case?
