### ISSUE TITLE
Are all timezones included?

### ISSUE THREAD

**Issue by msdesign21** [andytlr/homeslice#25]
I tried adding 'Cape Town' or the 'South African time zone' but could not find it in the list. Are all timezones included? If not, can you add this one?

**Comment by andytlr** [comment]
Cape Town doesn't appear to be in the [source list of places](http://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

I can map cities to the timezone of other cities. So if, for example, Cape Town always keeps the same time as Johannesburg, I could add Cape Town.

I just want to be careful about these special cases as I don't want to be keeping track of when places adhere to daylight savings manually.

**Comment by andytlr** [comment]
It seems as though DST isn't observed in either city. So I'll map Cape Town to Johannesburg.

**Comment by msdesign21** [comment]
Awesome! Thanks! :+1:

**Comment by bryceadams** [comment]
:+1: :+1:

**Comment by andytlr** [comment]
@msdesign21 @bryceadams,
I'm doing this right now. :earth_africa: :ok_hand:
